# Generated by Django 3.1.1 on 2021-04-13 13:40

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import exchangeguide.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_language', models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français'), ('ZH', '中文'), ('HI', 'हिन्दी'), ('BN', 'বাংলা'), ('PT', 'Português'), ('RU', 'Русский язык'), ('JA', '日本語')], default='EN', help_text='Please select the language you will use for the post.', max_length=2, verbose_name='Guide language')),
                ('country', models.CharField(choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], default='CH', help_text='Select the country you want to present.', max_length=2, unique=True, verbose_name='Country')),
                ('slug', models.SlugField(default='countryguide', help_text='Slug consisting of country', unique=True, verbose_name='Slug')),
                ('last_updated', models.DateField(auto_now=True, help_text='Date guide was last updated.', verbose_name='Last updated')),
                ('spoken_language', models.CharField(help_text='Enter the languages spoken in this country.', max_length=50, verbose_name='Spoken language')),
                ('population', models.CharField(help_text='Enter the population of this country.', max_length=15, verbose_name='Population')),
                ('capital_city', models.CharField(help_text='Enter the capital city of this country.', max_length=20, verbose_name='Capital city')),
                ('currency', models.CharField(help_text='Enter what currency (money) is being used in this country.', max_length=20, verbose_name='Currency')),
                ('short_description', models.CharField(default='Check out this amazing country', help_text='Enter a short description about what makes this country special.', max_length=55, verbose_name='Short description')),
                ('country_guide_content', django_ckeditor_5.fields.CKEditor5Field(help_text='Describe the most important things and aspects about the country (e.g. food, people, culture, school, ...)', verbose_name='Main content')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeblog.blogauthor', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=exchangeguide.models.get_image_filename)),
                ('image_description', models.CharField(help_text='Briefly describe what can be seen in picture.', max_length=50)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exchangeguide.countryguidepost')),
            ],
        ),
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter the title of the Post', max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(default='guidePost', help_text='Slug consisting of title of guide post.', unique=True)),
                ('guide_content', django_ckeditor_5.fields.CKEditor5Field(help_text='Here is the place to write the actual guide itself.', verbose_name='Guide content')),
                ('short_description', models.TextField(help_text='Enter a short description about what this tutorial is about.', max_length=250, verbose_name='Short description')),
                ('thumbnail_picture', imagekit.models.fields.ProcessedImageField(upload_to='guide_thumbnails/', verbose_name='Thumbnail picture')),
                ('main_guide_post_number', models.IntegerField(blank=True, help_text='If post is part of the main step by step guide, enter its number in the order here.', null=True, unique=True, verbose_name='Main Guide Post Number')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeblog.blogauthor', verbose_name='Author')),
            ],
        ),
    ]
