# Generated by Django 2.2.4 on 2020-02-06 02:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchangeblog', '0006_auto_20200206_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Please enter the title of the Post')),
                ('guide_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('short_description', models.TextField(verbose_name='Enter a short description about what this tutorial is about.')),
                ('thumbnail_picture', imagekit.models.fields.ProcessedImageField(upload_to='guide_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='CountryGuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_language', models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français')], default='EN', help_text='Please enter the language you will use for the post.', max_length=2)),
                ('country', models.CharField(choices=[('CH', '🇨🇳China'), ('US', '🇺🇸USA'), ('UK', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand')], default='CH', help_text='Select the country you want to present.', max_length=2)),
                ('country_guide_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Date guide was last updated.')),
                ('spoken_language', models.CharField(max_length=50, verbose_name='Enter the languages spoken in this country.')),
                ('population', models.CharField(max_length=15, verbose_name='Enter the population of this country.')),
                ('capital_city', models.CharField(max_length=20, verbose_name='Enter the capital city of this country.')),
                ('currency', models.CharField(max_length=20, verbose_name='Enter what currency (money) is being used in this country.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogAuthor')),
            ],
        ),
    ]
