# Generated by Django 2.2.4 on 2020-09-16 14:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import exchangeguide.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_language', models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français')], default='EN', help_text='Please select the language you will use for the post.', max_length=2)),
                ('country', models.CharField(choices=[('CH', '🇨🇳China'), ('US', '🇺🇸USA'), ('UK', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand')], default='CH', help_text='Select the country you want to present.', max_length=2)),
                ('slug', models.SlugField(default='countryguide', unique=True, verbose_name='Slug consisting of country')),
                ('last_updated', models.DateField(auto_now=True, help_text='Date guide was last updated.')),
                ('spoken_language', models.CharField(help_text='Enter the languages spoken in this country.', max_length=50)),
                ('population', models.CharField(help_text='Enter the population of this country.', max_length=15)),
                ('capital_city', models.CharField(help_text='Enter the capital city of this country.', max_length=20)),
                ('currency', models.CharField(help_text='Enter what currency (money) is being used in this country.', max_length=20)),
                ('short_description', models.CharField(default='Check out this amazing country', help_text='Enter a short description about what makes this country special.', max_length=55)),
                ('country_guide_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Please select the Country Guide Template from the template button (Third symbol at top left).', verbose_name='Main content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogAuthor')),
            ],
        ),
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Please enter the title of the Post')),
                ('slug', models.SlugField(default='guidePost', unique=True, verbose_name='Slug consisting of title of guide post.')),
                ('guide_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('short_description', models.TextField(max_length=250, verbose_name='Enter a short description about what this tutorial is about.')),
                ('thumbnail_picture', imagekit.models.fields.ProcessedImageField(upload_to='guide_thumbnails/')),
                ('main_guide_post_number', models.IntegerField(blank=True, help_text='If post is part of the main step by step guide, enter its number in the order here.', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=exchangeguide.models.get_image_filename)),
                ('image_description', models.CharField(help_text='Briefly describe what can be seen in picture.', max_length=50)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exchangeguide.CountryGuidePost')),
            ],
        ),
    ]
