# Generated by Django 3.2 on 2021-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepost',
            name='title',
            field=models.CharField(help_text='Please enter the title of the Post', max_length=70, verbose_name='Title'),
        ),
    ]
