# Generated by Django 2.2.4 on 2020-02-06 05:23

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryguidepost',
            name='short_description',
            field=models.CharField(default='Check out this amazing country', help_text='Enter a short description about what makes this country special.', max_length=55),
        ),
        migrations.AddField(
            model_name='countryguidepost',
            name='slug',
            field=models.SlugField(default='countryguide', unique=True, verbose_name='Slug consisting of country'),
        ),
        migrations.AddField(
            model_name='countryguidepost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(default='thumbnail', upload_to='country_guide_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='capital_city',
            field=models.CharField(help_text='Enter the capital city of this country.', max_length=20),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='currency',
            field=models.CharField(help_text='Enter what currency (money) is being used in this country.', max_length=20),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='last_updated',
            field=models.DateField(auto_now=True, help_text='Date guide was last updated.'),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='population',
            field=models.CharField(help_text='Enter the population of this country.', max_length=15),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='spoken_language',
            field=models.CharField(help_text='Enter the languages spoken in this country.', max_length=50),
        ),
    ]
