# Generated by Django 3.1.1 on 2021-02-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0004_auto_20210117_1331'),
        ('exchangeguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeblog.blogauthor'),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchangeblog.blogauthor'),
        ),
    ]
