# Generated by Django 2.2.4 on 2020-02-07 12:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import exchangeguide.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0002_auto_20200206_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepost',
            name='country_guide_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Main content'),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(default='thumbnail', upload_to='country_guide/thumbnails'),
        ),
        migrations.CreateModel(
            name='SlideShowImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='slideshow', upload_to=exchangeguide.models.get_image_filename)),
                ('image_description', models.CharField(help_text='Briefly describe what can be seen in picture.', max_length=50)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exchangeguide.CountryGuidePost')),
            ],
        ),
    ]
