# Generated by Django 3.1.1 on 2021-03-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0002_auto_20210204_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepost',
            name='country',
            field=models.CharField(choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], default='CH', help_text='Select the country you want to present.', max_length=2),
        ),
        migrations.AlterField(
            model_name='countryguidepost',
            name='guide_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français'), ('ZH', '中文'), ('HI', 'हिन्दी'), ('BN', 'বাংলা'), ('PT', 'Português'), ('RU', 'Русский язык'), ('JA', '日本語')], default='EN', help_text='Please select the language you will use for the post.', max_length=2),
        ),
    ]
