# Generated by Django 2.2.4 on 2020-02-12 10:21

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0004_auto_20200208_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepost',
            name='slug',
            field=models.SlugField(default='guidePost', unique=True, verbose_name='Slug consisting of title of guide post.'),
        ),
        migrations.AlterField(
            model_name='guidepost',
            name='short_description',
            field=models.TextField(max_length=400, verbose_name='Enter a short description about what this tutorial is about.'),
        ),
        migrations.AlterField(
            model_name='slideshowimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='country_guide/slideshow/'),
        ),
    ]
