# Generated by Django 2.2.4 on 2020-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0005_auto_20200212_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepost',
            name='short_description',
            field=models.TextField(max_length=250, verbose_name='Enter a short description about what this tutorial is about.'),
        ),
    ]
