# Generated by Django 2.2.4 on 2020-04-17 10:20

import ckeditor_uploader.fields
from django.db import migrations
import exchangeguide.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeguide', '0007_guidepost_main_guide_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryguidepost',
            name='country_guide_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Please select the Country Guide Template from the template button (Third symbol at top left).', verbose_name='Main content'),
        ),
        migrations.AlterField(
            model_name='slideshowimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=exchangeguide.models.get_image_filename),
        ),
    ]
