# Generated by Django 3.1.1 on 2021-04-13 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The registration code will be created automatically, so this field is disabled.', max_length=7, unique=True, verbose_name='Registration Code')),
                ('has_blogauthor_permission', models.BooleanField(default=True, help_text='Specify wether the user using this code will be able to add blog posts.', verbose_name='Has blogauthor permission')),
                ('has_guidepost_permission', models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add guide posts.', verbose_name='Has guidepost permission')),
                ('has_countryguide_permission', models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add a country guide about their country.', verbose_name='Has countryguidepost permission')),
                ('allowed_countries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], help_text='The allowed countries the author can write about when creating a country guide post.', max_length=26, null=True, verbose_name='Allowed countries')),
                ('expiry_date', models.DateField(default=datetime.datetime(2021, 5, 13, 15, 40, 10, 180648), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.', verbose_name='Expiry date')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Used by')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
    ]
