# Generated by Django 3.1.1 on 2021-01-17 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The registration code will be created automatically, so this field is disabled.', max_length=7, unique=True, verbose_name='Registration Code')),
                ('has_blogauthor_permission', models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add blog posts.')),
                ('has_guidepost_permission', models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add guide and country guide posts.')),
                ('expiry_date', models.DateField(default=datetime.datetime(2021, 2, 16, 13, 31, 58, 338382), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
