# Generated by Django 3.1.1 on 2021-02-03 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationcode',
            options={'ordering': ['-expiry_date']},
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='has_countryguide_permission',
            field=models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add a country guide about their country.'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 19, 45, 44, 600323), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='has_guidepost_permission',
            field=models.BooleanField(default=False, help_text='Specify wether the user using this code will be able to add guide posts.'),
        ),
    ]
