# Generated by Django 3.1.1 on 2021-02-04 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210203_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 10, 43, 2, 680638), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.'),
        ),
    ]
