# Generated by Django 3.1.1 on 2021-03-08 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210204_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 21, 12, 54, 710723), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='has_blogauthor_permission',
            field=models.BooleanField(default=True, help_text='Specify wether the user using this code will be able to add blog posts.'),
        ),
    ]
