# Generated by Django 3.2 on 2021-05-10 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_registrationcode_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='max_post_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='The maximum number of posts this author can write.', verbose_name='Max Post Count'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 9, 19, 34, 41, 991894), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.', verbose_name='Expiry date'),
        ),
    ]
