# Generated by Django 3.1.1 on 2021-03-09 16:53

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210309_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='allowed_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], help_text='The allowed countries the author can write about when creating a country guide post.', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 17, 53, 20, 197501), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.'),
        ),
    ]
