# Generated by Django 3.1.1 on 2021-03-09 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210309_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 21, 27, 5, 163412), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.'),
        ),
    ]
