# Generated by Django 3.2 on 2021-07-06 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_registrationcode_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 23, 18, 4, 202070), help_text='The date upon which this code will be invalid, is automatically populated, but you can adjust it if you want.', verbose_name='Expiry date'),
        ),
    ]
