#!/usr/bin/env python
# -*- coding: utf-8 -*- 

from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django.utils.translation import get_language

LANGUAGE_CHOICES = [
        ('EN', 'English'),
        ('DE', 'Deutsch'),
        ('IT', 'Italiano'),
        ('FR', 'Français'),
        ('ZH', '中文'),
        ('HI', 'हिन्दी'),
        ('BN', 'বাংলা'),
        ('PT', 'Português'),
        ('RU', 'Русский язык'),
        ('JA', '日本語'),
]

def get_year_choices():
    YEAR_CHOICES = []
    startYear = datetime(1961, 1, 1)
    endYear = datetime.now().year
    years = range(startYear.year, endYear+1)
    for year in years:
        YEAR_CHOICES.append((year, year))
    return YEAR_CHOICES

COUNTRY_CHOICES = [
	('AF', _('🇦🇫Afghanistan')),
	('AL', _('🇦🇱Albania')),
	('DZ', _('🇩🇿Algeria')),
	('AD', _('🇦🇩Andorra')),
	('AO', _('🇦🇴Angola')),
	('AQ', _('🇦🇶Antarctica')),
	('AR', _('🇦🇷Argentina')),
	('AM', _('🇦🇲Armenia')),
	('AW', _('🇦🇼Aruba')),
	('AU', _('🇦🇺Australia')),
	('AT', _('🇦🇹Austria')),
	('AZ', _('🇦🇿Azerbaijan')),
	('BS', _('🇧🇸Bahamas')),
	('BH', _('🇧🇭Bahrain')),
	('BD', _('🇧🇩Bangladesh')),
	('BB', _('🇧🇧Barbados')),
	('BY', _('🇧🇾Belarus')),
	('BE', _('🇧🇪Belgium')),
	('BZ', _('🇧🇿Belize')),
	('BJ', _('🇧🇯Benin')),
	('BM', _('🇧🇲Bermuda')),
	('BT', _('🇧🇹Bhutan')),
	('BO', _('🇧🇴Bolivia')),
	('BA', _('🇧🇦Bosnia & Herzegovina')),
	('BW', _('🇧🇼Botswana')),
	('BR', _('🇧🇷Brazil')),
	('BN', _('🇧🇳Brunei')),
	('BG', _('🇧🇬Bulgaria')),
	('BF', _('🇧🇫Burkina Faso')),
	('BI', _('🇧🇮Burundi')),
	('KH', _('🇰🇭Cambodia')),
	('CM', _('🇨🇲Cameroon')),
	('CA', _('🇨🇦Canada')),
	('CV', _('🇨🇻Cape Verde')),
	('CF', _('🇨🇫Central African Republic')),
	('TD', _('🇹🇩Chad')),
	('CL', _('🇨🇱Chile')),
	('CN', _('🇨🇳China')),
	('CO', _('🇨🇴Colombia')),
	('KM', _('🇰🇲Comoros')),
	('CG', _('🇨🇬Congo - Brazzaville')),
	('CD', _('🇨🇩Congo - Kinshasa')),
	('CR', _('🇨🇷Costa Rica')),
	('CI', _('🇨🇮Côte d’Ivoire')),
	('HR', _('🇭🇷Croatia')),
	('CU', _('🇨🇺Cuba')),
	('CW', _('🇨🇼Curaçao')),
	('CY', _('🇨🇾Cyprus')),
	('CZ', _('🇨🇿Czechia')),
	('DK', _('🇩🇰Denmark')),
	('DJ', _('🇩🇯Djibouti')),
	('DM', _('🇩🇲Dominica')),
	('DO', _('🇩🇴Dominican Republic')),
	('EC', _('🇪🇨Ecuador')),
	('EG', _('🇪🇬Egypt')),
	('SV', _('🇸🇻El Salvador')),
	('GQ', _('🇬🇶Equatorial Guinea')),
	('ER', _('🇪🇷Eritrea')),
	('EE', _('🇪🇪Estonia')),
	('SZ', _('🇸🇿Eswatini')),
	('ET', _('🇪🇹Ethiopia')),
	('FK', _('🇫🇰Falkland Islands')),
	('FO', _('🇫🇴Faroe Islands')),
	('FJ', _('🇫🇯Fiji')),
	('FI', _('🇫🇮Finland')),
	('FR', _('🇫🇷France')),
	('GF', _('🇬🇫French Guiana')),
	('PF', _('🇵🇫French Polynesia')),
	('GA', _('🇬🇦Gabon')),
	('GM', _('🇬🇲Gambia')),
	('GE', _('🇬🇪Georgia')),
	('DE', _('🇩🇪Germany')),
	('GH', _('🇬🇭Ghana')),
	('GI', _('🇬🇮Gibraltar')),
	('GR', _('🇬🇷Greece')),
	('GL', _('🇬🇱Greenland')),
	('GD', _('🇬🇩Grenada')),
	('GP', _('🇬🇵Guadeloupe')),
	('GU', _('🇬🇺Guam')),
	('GT', _('🇬🇹Guatemala')),
	('GG', _('🇬🇬Guernsey')),
	('GN', _('🇬🇳Guinea')),
	('GW', _('🇬🇼Guinea-Bissau')),
	('GY', _('🇬🇾Guyana')),
	('HT', _('🇭🇹Haiti')),
	('HN', _('🇭🇳Honduras')),
	('HK', _('🇭🇰Hong Kong SAR China')),
	('HU', _('🇭🇺Hungary')),
	('IS', _('🇮🇸Iceland')),
	('IN', _('🇮🇳India')),
	('ID', _('🇮🇩Indonesia')),
	('IR', _('🇮🇷Iran')),
	('IQ', _('🇮🇶Iraq')),
	('IE', _('🇮🇪Ireland')),
	('IM', _('🇮🇲Isle of Man')),
	('IL', _('🇮🇱Israel')),
	('IT', _('🇮🇹Italy')),
	('JM', _('🇯🇲Jamaica')),
	('JP', _('🇯🇵Japan')),
	('JE', _('🇯🇪Jersey')),
	('JO', _('🇯🇴Jordan')),
	('KZ', _('🇰🇿Kazakhstan')),
	('KE', _('🇰🇪Kenya')),
	('KI', _('🇰🇮Kiribati')),
	('KW', _('🇰🇼Kuwait')),
	('KG', _('🇰🇬Kyrgyzstan')),
	('LA', _('🇱🇦Laos')),
	('LV', _('🇱🇻Latvia')),
	('LB', _('🇱🇧Lebanon')),
	('LS', _('🇱🇸Lesotho')),
	('LR', _('🇱🇷Liberia')),
	('LY', _('🇱🇾Libya')),
	('LI', _('🇱🇮Liechtenstein')),
	('LT', _('🇱🇹Lithuania')),
	('LU', _('🇱🇺Luxembourg')),
	('MO', _('🇲🇴Macao SAR China')),
	('MG', _('🇲🇬Madagascar')),
	('MW', _('🇲🇼Malawi')),
	('MY', _('🇲🇾Malaysia')),
	('MV', _('🇲🇻Maldives')),
	('ML', _('🇲🇱Mali')),
	('MT', _('🇲🇹Malta')),
	('MH', _('🇲🇭Marshall Islands')),
	('MQ', _('🇲🇶Martinique')),
	('MR', _('🇲🇷Mauritania')),
	('MU', _('🇲🇺Mauritius')),
	('YT', _('🇾🇹Mayotte')),
	('MX', _('🇲🇽Mexico')),
	('FM', _('🇫🇲Micronesia')),
	('MD', _('🇲🇩Moldova')),
	('MC', _('🇲🇨Monaco')),
	('MN', _('🇲🇳Mongolia')),
	('ME', _('🇲🇪Montenegro')),
	('MS', _('🇲🇸Montserrat')),
	('MA', _('🇲🇦Morocco')),
	('MZ', _('🇲🇿Mozambique')),
	('MM', _('🇲🇲Myanmar (Burma)')),
	('NA', _('🇳🇦Namibia')),
	('NR', _('🇳🇷Nauru')),
	('NP', _('🇳🇵Nepal')),
	('NL', _('🇳🇱Netherlands')),
	('NC', _('🇳🇨New Caledonia')),
	('NZ', _('🇳🇿New Zealand')),
	('NI', _('🇳🇮Nicaragua')),
	('NE', _('🇳🇪Niger')),
	('NG', _('🇳🇬Nigeria')),
	('NU', _('🇳🇺Niue')),
	('NF', _('🇳🇫Norfolk Island')),
	('KP', _('🇰🇵North Korea')),
	('MK', _('🇲🇰North Macedonia')),
	('NO', _('🇳🇴Norway')),
	('OM', _('🇴🇲Oman')),
	('PK', _('🇵🇰Pakistan')),
	('PW', _('🇵🇼Palau')),
	('PS', _('🇵🇸Palestinian Territories')),
	('PA', _('🇵🇦Panama')),
	('PG', _('🇵🇬Papua New Guinea')),
	('PY', _('🇵🇾Paraguay')),
	('PE', _('🇵🇪Peru')),
	('PH', _('🇵🇭Philippines')),
	('PN', _('🇵🇳Pitcairn Islands')),
	('PL', _('🇵🇱Poland')),
	('PT', _('🇵🇹Portugal')),
	('PR', _('🇵🇷Puerto Rico')),
	('QA', _('🇶🇦Qatar')),
	('RE', _('🇷🇪Réunion')),
	('RO', _('🇷🇴Romania')),
	('RU', _('🇷🇺Russia')),
	('RW', _('🇷🇼Rwanda')),
	('WS', _('🇼🇸Samoa')),
	('SM', _('🇸🇲San Marino')),
	('ST', _('🇸🇹São Tomé & Príncipe')),
	('SA', _('🇸🇦Saudi Arabia')),
	('SN', _('🇸🇳Senegal')),
	('RS', _('🇷🇸Serbia')),
	('SC', _('🇸🇨Seychelles')),
	('SL', _('🇸🇱Sierra Leone')),
	('SG', _('🇸🇬Singapore')),
	('SX', _('🇸🇽Sint Maarten')),
	('SK', _('🇸🇰Slovakia')),
	('SI', _('🇸🇮Slovenia')),
	('SB', _('🇸🇧Solomon Islands')),
	('SO', _('🇸🇴Somalia')),
	('ZA', _('🇿🇦South Africa')),
	('KR', _('🇰🇷South Korea')),
	('SS', _('🇸🇸South Sudan')),
	('ES', _('🇪🇸Spain')),
	('LK', _('🇱🇰Sri Lanka')),
	('SH', _('🇸🇭St. Helena')),
	('LC', _('🇱🇨St. Lucia')),
	('MF', _('🇲🇫St. Martin')),
	('SD', _('🇸🇩Sudan')),
	('SR', _('🇸🇷Suriname')),
	('SE', _('🇸🇪Sweden')),
	('CH', _('🇨🇭Switzerland')),
	('SY', _('🇸🇾Syria')),
	('TW', _('🇹🇼Taiwan')),
	('TJ', _('🇹🇯Tajikistan')),
	('TZ', _('🇹🇿Tanzania')),
	('TH', _('🇹🇭Thailand')),
	('TL', _('🇹🇱Timor-Leste')),
	('TG', _('🇹🇬Togo')),
	('TK', _('🇹🇰Tokelau')),
	('TO', _('🇹🇴Tonga')),
	('TT', _('🇹🇹Trinidad & Tobago')),
	('TN', _('🇹🇳Tunisia')),
	('TR', _('🇹🇷Turkey')),
	('TM', _('🇹🇲Turkmenistan')),
	('TC', _('🇹🇨Turks & Caicos Islands')),
	('TV', _('🇹🇻Tuvalu')),
	('UG', _('🇺🇬Uganda')),
	('UA', _('🇺🇦Ukraine')),
	('AE', _('🇦🇪United Arab Emirates')),
	('GB', _('🇬🇧United Kingdom')),
	('US', _('🇺🇸United States')),
	('UY', _('🇺🇾Uruguay')),
	('UZ', _('🇺🇿Uzbekistan')),
	('VU', _('🇻🇺Vanuatu')),
	('VA', _('🇻🇦Vatican City')),
	('VE', _('🇻🇪Venezuela')),
	('VN', _('🇻🇳Vietnam')),
	('WF', _('🇼🇫Wallis & Futuna')),
	('EH', _('🇪🇭Western Sahara')),
	('YE', _('🇾🇪Yemen')),
	('ZM', _('🇿🇲Zambia')),
	('ZW', _('🇿🇼Zimbabwe')),
]