# Generated by Django 2.2.4 on 2020-09-16 14:43

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=15, unique=True)),
                ('social_media_link', models.CharField(blank=True, help_text='Please paste the url of your social media page (optional).', max_length=300, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(help_text='Please enter a short description of yourself.', max_length=400)),
                ('allowed_posts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('can_edit_blogpost', 'Can create, update and delete a blogpost '),),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter the title of the Blog Post.', max_length=50)),
                ('date_of_creation', models.DateField(default=datetime.date.today, help_text='Enter date of creation of post.')),
                ('slug', models.SlugField(help_text='Enter a slug according to the title of the post', unique=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français')], default='EN', help_text='Please enter the language you will use for the post.', max_length=2)),
                ('country', models.CharField(choices=[('CH', '🇨🇳China'), ('US', '🇺🇸USA'), ('UK', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand')], default='CH', help_text='Select the exchange country.', max_length=2)),
                ('short_description', models.TextField(help_text='Enter a short description of what the blog post is about.', max_length=150)),
                ('blogcontent', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail_picture', imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbnails/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogAuthor')),
            ],
            options={
                'verbose_name_plural': 'blog posts',
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
