# Generated by Django 2.2.4 on 2019-08-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the name of the author.', max_length=20)),
                ('bio', models.TextField(help_text='Please enter a short description of yourself.')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter the title of the Blog Post.', max_length=50)),
                ('date_of_creation', models.DateField(help_text='Enter date of creation of post.')),
                ('blogcontent', models.TextField(help_text='Please enter the text you want to publish.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogAuthor')),
            ],
            options={
                'verbose_name_plural': 'blog posts',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(help_text='Please enter a short description of the picture.', max_length=150)),
                ('image', models.ImageField(upload_to=None)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogPost')),
            ],
        ),
    ]
