# Generated by Django 3.1.1 on 2021-04-13 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import imagekit.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=19, unique=True, verbose_name='Name')),
                ('social_media_link', models.URLField(blank=True, help_text='Please paste the url of your social media page (optional).', max_length=300, null=True, verbose_name='Social Media Link')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('bio', models.TextField(help_text='Please enter a short description of yourself.', max_length=400, verbose_name='as in biography')),
                ('allowed_posts', models.PositiveSmallIntegerField(default=1, verbose_name='Allowed posts')),
                ('allowed_countries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], help_text='The countries this author can write about in a country guide post.', max_length=26, null=True, verbose_name='Allowed countries')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter the title of the Blog Post.', max_length=50, verbose_name='Title')),
                ('date_of_creation', models.DateField(default=datetime.date.today, help_text='Enter date of creation of post.', verbose_name='Date of creation')),
                ('slug', models.SlugField(help_text='Enter a slug according to the title of the post', unique=True, verbose_name='Slug')),
                ('language', models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français'), ('ZH', '中文'), ('HI', 'हिन्दी'), ('BN', 'বাংলা'), ('PT', 'Português'), ('RU', 'Русский язык'), ('JA', '日本語')], default='EN', help_text='Please enter the language you will use for the post.', max_length=2, verbose_name='Language')),
                ('country', models.CharField(choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], default='CH', help_text='Select the exchange country.', max_length=2, verbose_name='Country')),
                ('short_description', models.TextField(help_text='Enter a short description of what the blog post is about.', max_length=150, verbose_name='Short description')),
                ('blogcontent', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Blog content')),
                ('thumbnail_picture', imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbnails/', verbose_name='Thumbnail picture')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.blogauthor', verbose_name='Blog Author')),
            ],
            options={
                'verbose_name_plural': 'blog posts',
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
