# Generated by Django 3.2 on 2021-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='allowed_posts',
            field=models.PositiveSmallIntegerField(default=1, help_text='The maximum number of posts this author can write.', verbose_name='Allowed posts'),
        ),
    ]
