# Generated by Django 2.2.4 on 2019-08-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostImages',
            new_name='BlogPostImage',
        ),
    ]
