# Generated by Django 2.2.4 on 2020-01-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(default='Description not found.', max_length=200),
        ),
    ]
