# Generated by Django 3.1.1 on 2020-12-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['name']},
        ),
    ]
