# Generated by Django 2.2.4 on 2020-01-26 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0002_blogpost_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(help_text='Please enter a short description of yourself.', max_length=400),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='country',
            field=models.CharField(choices=[('CH', '🇨🇳China'), ('US', '🇺🇸USA'), ('UK', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand')], default='CH', help_text='Select the exchange country.', max_length=2),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_of_creation',
            field=models.DateField(default=datetime.date.today, help_text='Enter date of creation of post.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(help_text='Enter a short description of what the blog post is about.', max_length=150),
        ),
    ]
