# Generated by Django 3.2 on 2021-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0002_alter_blogauthor_allowed_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Please enter the title of the Blog Post.', max_length=70, verbose_name='Title'),
        ),
    ]
