# Generated by Django 3.1.1 on 2020-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0002_auto_20201222_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='allowed_posts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
