# Generated by Django 2.2.4 on 2019-08-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0002_auto_20190818_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_of_creation'], 'verbose_name_plural': 'blog posts'},
        ),
    ]
