# Generated by Django 2.2.4 on 2020-01-28 04:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0003_auto_20200126_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogcontent',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
