# Generated by Django 2.2.4 on 2019-09-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0003_auto_20190820_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Enter a subheader (optional)', max_length=50)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogPost')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
