# Generated by Django 2.2.4 on 2019-10-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0003_auto_20190820_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.CharField(choices=[('CH', '🇨🇳China'), ('US', '🇺🇸USA'), ('UK', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand')], default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français')], default='EN', max_length=2),
        ),
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
