# Generated by Django 2.2.4 on 2020-01-29 02:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0004_auto_20200128_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogcontent',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
