# Generated by Django 3.2 on 2021-07-03 10:43

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0004_auto_20210703_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Add the link to your Facebook page here (optional).', max_length=300, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Add the link to your Instagram page here (optional).', max_length=300, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='tiktok_link',
            field=models.URLField(blank=True, help_text='Add the link to your Tik Tok page here (optional).', max_length=300, null=True, verbose_name='Tik Tok Link'),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='website_link',
            field=models.URLField(blank=True, help_text='Add the link to your website here (optional).', max_length=300, null=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/default_profile_image.jpg', help_text='Select a profile image for your account (optional)', upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
