# Generated by Django 3.1.1 on 2021-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0004_auto_20210117_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='social_media_link',
            field=models.URLField(blank=True, help_text='Please paste the url of your social media page (optional).', max_length=300, null=True),
        ),
    ]
