# Generated by Django 2.2.4 on 2019-09-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0004_auto_20190918_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostParagraph',
        ),
    ]
