# Generated by Django 2.2.4 on 2019-09-27 11:31

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0005_delete_blogpostparagraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogcontent',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(default='This blog post is outdated. If you are the author, please update it', verbose_name='TextField'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 9, 27), help_text='Enter date of creation of post.'),
        ),
    ]
