# Generated by Django 2.2.4 on 2019-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0005_auto_20191016_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_of_creation'], 'permissions': (('can_create_post', 'Create a blog post'),), 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, help_text='Enter date of creation of post.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français')], default='EN', help_text='Please enter the language you will use for the post.', max_length=2),
        ),
    ]
