# Generated by Django 2.2.4 on 2020-02-06 02:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0005_auto_20200129_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog_thumbnails/'),
        ),
    ]
