# Generated by Django 3.1.1 on 2021-03-09 16:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0006_auto_20210308_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='allowed_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], help_text='The countries this author can write about in a country guide post.', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='country',
            field=models.CharField(choices=[('CN', '🇨🇳China'), ('US', '🇺🇸USA'), ('GB', '🇬🇧United Kingdom'), ('DE', '🇩🇪Germany'), ('IT', '🇮🇹Italy'), ('FR', '🇫🇷France'), ('TH', '🇹🇭Thailand'), ('JP', '🇯🇵Japan'), ('IN', '🇮🇳India')], default='CH', help_text='Select the exchange country.', max_length=2),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('IT', 'Italiano'), ('FR', 'Français'), ('ZH', '中文'), ('HI', 'हिन्दी'), ('BN', 'বাংলা'), ('PT', 'Português'), ('RU', 'Русский язык'), ('JA', '日本語')], default='EN', help_text='Please enter the language you will use for the post.', max_length=2),
        ),
    ]
