# Generated by Django 2.2.4 on 2020-02-06 05:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0006_auto_20200206_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
