# Generated by Django 2.2.4 on 2019-09-27 11:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0006_auto_20190927_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='TextField'),
        ),
    ]
