# Generated by Django 3.2 on 2021-07-06 21:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0006_alter_blogauthor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Select a profile image for your account (optional)', null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
