# Generated by Django 2.2.4 on 2019-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0007_blogauthor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=20),
        ),
    ]
