# Generated by Django 2.2.4 on 2020-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0007_auto_20200206_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='social_media_link',
            field=models.CharField(blank=True, help_text='Please paste the url of your social media page (optional).', max_length=300, null=True),
        ),
    ]
