# Generated by Django 2.2.4 on 2019-11-10 08:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('exchangeblog', '0008_auto_20191019_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
