# Generated by Django 2.2.4 on 2019-11-08 05:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0008_auto_20191019_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
