# Generated by Django 2.0.1 on 2019-11-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0008_auto_20191019_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogcontent',
        ),
    ]
