# Generated by Django 2.0.1 on 2019-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0009_remove_blogpost_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogcontent',
            field=models.CharField(max_length=50, null=True, verbose_name='Placeholder'),
        ),
    ]
