# Generated by Django 2.2.4 on 2019-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0009_blogpost_thumbnail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=models.ImageField(default='/media/uploads/tilman/2019/10/15/img_2092.jpeg', upload_to='tumbnails/%Y', verbose_name='Thumbnail Picture'),
        ),
    ]
