# Generated by Django 2.2.4 on 2019-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0010_auto_20191110_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='allowed_posts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
