# Generated by Django 2.2.4 on 2019-11-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0012_auto_20191117_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=models.ImageField(default='uploads/tilman/2019/10/15/img_2092.jpeg', upload_to='thumbnails/%Y', verbose_name='Thumbnail Picture'),
        ),
    ]
