# Generated by Django 2.2.4 on 2019-11-22 09:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0014_auto_20191118_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(default='uploads/tilman/2019/10/15/img_2092.jpeg', upload_to='thumbnails/', verbose_name='Thumbnail Picture'),
        ),
    ]
