# Generated by Django 2.2.4 on 2019-11-23 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0016_auto_20191123_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangeblog.BlogAuthor'),
        ),
    ]
