# Generated by Django 2.2.4 on 2019-11-23 02:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0017_auto_20191123_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbnails/', verbose_name='Thumbnail Picture'),
        ),
    ]
