# Generated by Django 2.2.4 on 2019-11-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0018_auto_20191123_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=models.ImageField(default='thumbnails/IMG_2090.jpeg', height_field=500, upload_to='thumbnails/', verbose_name='Thumbnail Picture', width_field=500),
        ),
    ]
