# Generated by Django 2.2.4 on 2019-11-24 02:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0019_auto_20191124_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(default='thumbnails/IMG_2090.jpeg', null=True, upload_to='thumbnails/'),
        ),
    ]
