# Generated by Django 2.2.4 on 2019-11-24 11:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0023_auto_20191124_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
