# Generated by Django 2.2.4 on 2019-11-24 11:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0024_auto_20191124_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/thumbnails/'),
        ),
    ]
