# Generated by Django 2.2.4 on 2019-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0026_auto_20191127_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='name_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Please enter the title of the Blog Post.', max_length=30),
        ),
    ]
