# Generated by Django 2.2.4 on 2019-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0027_auto_20191202_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='name_slug',
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
