# Generated by Django 2.2.4 on 2019-12-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0028_auto_20191203_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='slug',
            new_name='name_slug',
        ),
    ]
