# Generated by Django 2.2.4 on 2019-12-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0029_auto_20191203_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='name_slug',
            new_name='slug',
        ),
    ]
