# Generated by Django 2.2.4 on 2019-12-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0030_auto_20191203_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['name'], 'permissions': (('can_create_post', 'Create a blog post'),)},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_of_creation'], 'verbose_name_plural': 'blog posts'},
        ),
    ]
