# Generated by Django 2.2.4 on 2019-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0031_auto_20191209_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['name'], 'permissions': (('can_edit_post', 'Can edit a blog post'),)},
        ),
    ]
