# Generated by Django 2.2.4 on 2019-12-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0032_auto_20191213_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'default_permissions': ('add_blogpost', 'change_blogpost', 'delete_blogpost'), 'ordering': ['name']},
        ),
    ]
