# Generated by Django 2.2.4 on 2019-12-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0033_auto_20191214_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['name'], 'permissions': (('can_edit_blogpost', 'Can create, update and delete a blogpost '),)},
        ),
    ]
