# Generated by Django 2.2.4 on 2019-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0034_auto_20191214_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.CharField(help_text='Please enter your author name (It will be displayed in articles you write).', max_length=15, unique=True),
        ),
    ]
