# Generated by Django 2.2.4 on 2019-12-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0035_auto_20191216_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_slug',
            field=models.SlugField(help_text='Enter a slug according to the title of the post', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
