# Generated by Django 2.2.4 on 2019-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0036_auto_20191221_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title_slug',
            field=models.SlugField(help_text='Enter a slug according to the title of the post', unique=True),
        ),
    ]
