# Generated by Django 2.2.4 on 2019-12-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeblog', '0037_auto_20191221_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title_slug',
            new_name='slug',
        ),
    ]
